services:
  backend:
    build:
      context: ./backend
    environment:
      - PORT=3000
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - API_KEY=${API_KEY}
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_API_KEY=${VITE_API_KEY}
    ports:
      - "8080:80"
    depends_on:
      - backend
